% =========================================================================
% Dynamic Tilt Estimation for Pen Tracking Using a Single
% Tri-Axial Accelerometer
%
% Author:
%   Aditya Ranjan Padhi
%
% Affiliation:
%   Signal Processing and Communications Research Center (SPCRC)
%   Indian Institute of Information Technology Hyderabad
%
% This code accompanies the publication:
%
% "Dynamic Tilt Estimation for Pen Tracking Using a Single
% Tri-Axial Accelerometer"
%
% Description:
%   Constrained optimization framework for dynamic tilt
%   estimation using only accelerometer measurements.
%
% Copyright (c) 2026 Aditya Ranjan Padhi
%
% This software is provided for academic and research use.
% If you use this code in your research, please cite the
% corresponding publication.
%
% =========================================================================

%% Enter Path to Motion File as generated by "Simulink_Model.slx"

FILEPATH = "";
load(FILEPATH)
% Example: load("Results\Circular_Motion\results_err_0_seed_1.mat")

%% Transformation Functions

function R = Rx(theta)
    R = [1         0               0      ;
         0    cosd(theta)    -sind(theta) ;
         0    sind(theta)     cosd(theta)];
end

function R = Ry(theta)
    R = [cosd(theta)    0    sind(theta) ;
              0         1         0      ;
        -sind(theta)    0    cosd(theta)];
end


%% Optimization Functions

function [theta, phi] = estimate_angles_constrained(ax, ay, az)
    
    % Gravitational acceleration (m/s^2)
    g = 9.80655;

    % Number of samples
    N = length(ax);
    
    % Output vectors
    % theta -> pitch
    % phi   -> roll
    theta = zeros(N,1);
    phi = zeros(N,1);
    
    % Angle limits (radians)
    lb = deg2rad([-90, -90]);   % [TH_min, PH_min]
    ub = deg2rad([ 90,  90]);   % [TH_max, PH_max]


    % Optimization settings
    opts = optimoptions('fmincon', 'Display','off', 'Algorithm','sqp');
    
    % Initial orientation estimate
    x0 = [-deg2rad(0); -deg2rad(0)];
    
    % Process each accelerometer sample
    for i = 1:N

        % Current accelerometer measurement
        a = [ax(i); ay(i); az(i)];

        % Angle between acceleration vector and gravity 
        % Equation (7)
        ratio = max(min(g/norm(a),1),-1);
        alpha = acos(ratio);
        
        % Rotate accelerometer measurements into the global frame
        % x(1) = theta (pitch)
        % x(2) = phi   (roll)

        % Equation (1)
        fax = @(x) ((ax(i).*cos(x(1)) + (ay(i).*sin(x(2)) + az(i).*cos(x(2))).*sin(x(1))));
        % Equation (2)
        fay = @(x) ((ay(i).*cos(x(2)) - az(i).*sin(x(2))));
        % Equation (3)
        faz = @(x) (-ax(i).*sin(x(1)) + (ay(i).*sin(x(2)) + az(i).*cos(x(2))).*cos(x(1)));

        % Transformed acceleration vector
        a_p = @(x) [fax(x) fay(x) faz(x)];
        
        % Magnitude of projected acceleration
        f = @(x) fax(x)^2 + fay(x)^2;

        % Unit vector perpendicular to projected acceleration
        % z = [0; 0; 1];
        % k = @(x) (cross(a_p,z));
        % k_norm = @(x) (sqrt(dot(k(x),k(x))));
        % k_unit = @(x) (k(x)/k_norm(x));
        k_unit  = @(x) [fay(x)/f(x); -fax(x)/f(x); 0];
        
        % Rodrigues rotation angle
        % Section III-B of the paper
        m_alpha = pi/2 - alpha;
        
        % Projection of acceleration onto the writing plane
        % using Rodrigues' rotation formula
        v_rot = @(x) (a_p(x)*cos(-m_alpha) + cross(k_unit(x), a_p(x))*sin(-m_alpha));

        % Extract x-component
        get_x1 = @(v) v(1);

        % Angle of projected acceleration in XY plane
        % Equation (8)
        x_ang = @(x) (acos(get_x1(v_rot(x))/norm(v_rot(x))));

 
        % Objective Function 1
        % Combines:
        %   1. Gravity constraint
        %   2. Planar motion constraint
        % Equations (4), (9), and (10)
        fun1 = @(x) ( ...
            (faz(x) - g)^2 ...
             + (cos((pi/2) + x_ang(x))*fax(x))^2 + (sin((pi/2) + x_ang(x))*fay(x))^2 ...
        );
        
        % Objective Function 2
        % Gravity-only objective
        fun2 = @(x) (faz(x) - g)^2;
         
        % Temporal continuity constraint
        % Restricts changes between successive samples to
        % improve robustness against noise.
        beta = deg2rad(0.1);
        A = [ eye(2) ; -eye(2) ];
        b = [ x0 + beta ; -x0 + beta ];
    
        % Solve constrained optimization problem
        try
            x = fmincon(fun1, x0, A, b, [], [], lb, ub, [], opts);
        catch
            x = fmincon(fun2, x0, A, b, [], [], lb, ub, [], opts);
        end

        % Store estimated angles
        theta(i) = x(1);
        phi(i) = x(2);
    
        % Use current estimate as next initial condition
        x0 = x;
       
    end
end


% =========================================================================
% Estimate orientation from accelerometer measurements
% =========================================================================
[theta, phi] = estimate_angles_constrained(sensor_acceleration_x, sensor_acceleration_y, sensor_acceleration_z);

% Convert to degrees for visualization
phi_c_deg   = rad2deg(phi);
theta_c_deg = rad2deg(theta);

%% Reverse Transformation for comparing results (Interpretebility)
% Corresponds to Figure 3 in the paper.
yr = zeros(1,length(theta_c_deg));
xr = zeros(1,length(phi_c_deg));
for i=1:length(phi_c_deg)
    R = Ry(-theta_c_deg(i))*Rx(-phi_c_deg(i));
    xr(i) = asind(R(3,2));
    yr(i) = atan2d(-R(3,1),R(3,3));
end


%% Plots
% Generates plots similar to Figure 3.
figure();
subplot(3,2,1);
plot(xr);
title("Calculated Roll")
xlabel('Time')
ylabel('\theta (deg)')
grid on;

subplot(3,2,3);
plot(true_roll);
title("Real Roll")
xlabel('Time')
ylabel('\theta (deg)')
grid on;

error_x = true_roll - (xr');
subplot(3,2,5);
plot(error_x);
title("Error in Roll")
xlabel('Time')
ylabel('\theta (deg)')
grid on;

subplot(3,2,2);
plot(yr)
title("Calculated Pitch")
xlabel('Time')
ylabel('\phi (deg)')
grid on;

subplot(3,2,4);
plot(true_pitch);
title("Real Pitch")
xlabel('Time')
ylabel('\phi (deg)')
grid on;

error_y = true_pitch - (yr');
subplot(3,2,6);
plot(error_y);
title("Error in Pitch")
xlabel('Time')
ylabel('\phi (deg)')
grid on;
